### Recuperar todas las películas
GET http://localhost:1234/movies

### Recuperar una película por id
GET http://localhost:1234/movies/33c2143c-5c40-11f0-8b9b-fc3497de0a7a

### Recuperar todas las películas de un género
GET http://localhost:1234/movies?genre=Sci-Fi

### Crear una película con POST
POST http://localhost:1234/movies
Content-Type: application/json

{
  "sql": "SELECT * FROM users",
  "title": "The Godfather",
  "year": 1972,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://example.com/godfather.jpg",
  "genre": ["Crime", "Drama"]
}

### Borrar una película
DELETE http://localhost:1234/movies/bb2f6c29-5c4d-11f0-8b9b-fc3497de0a7a

### Actualizar una película
PATCH http://localhost:1234/movies/bb2f6c29-5c4d-11f0-8b9b-fc3497de0a7a
Content-Type: application/json

{
  "year": 1972
}